#service.yaml

apiVersion: v1
kind: Service
metadata:
 name: vue-admin-service
 namespace: vue-admin
spec:
 selector:
   app: vue-admin
 ports:
   - protocol: TCP
     port: 8080
     targetPort: 80
 type: LoadBalancer