#service.yaml

apiVersion: v1
kind: Service
metadata:
 name: vue-admin-service
 namespace: default
spec:
 selector:
   app: vue-admin
 ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
 type: LoadBalancer